version: "3.7"

services:
  db_migrate:
    build: .
    env_file:
      - ./.env
    environment:
      PROCESS: migrate
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Kalam-002
      DB_NAME: applaud
  api:
    build: .
    ports:
      - "4000:3000"
    depends_on:
      - db_migrate
      - mysql
    env_file:
      - ./.env
    environment:
      PROCESS: api
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Kalam-002
      DB_NAME: applaud
  worker:
    build: .
    depends_on:
      - db_migrate
      - mysql
    env_file:
      - ./.env
    environment:
      PROCESS: worker
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Kalam-002
      DB_NAME: applaud
  mysql:
    image: mysql:5.7.25
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Kalam-002
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: applaud
    ports:
      - 32769:3306
    volumes:
      - ./.data/mysql:/var/lib/mysql